[tool.isort]
profile = "google"
line_length = 100

[tool.yapf]
based_on_style= "google"
column_limit = 100
SPLIT_BEFORE_DICT_SET_GENERATOR = false
SPLIT_BEFORE_CLOSING_BRACKET = false
BLANK_LINE_BEFORE_MODULE_DOCSTRING = true
SPACES_AROUND_POWER_OPERATOR = true
SPLIT_ALL_TOP_LEVEL_COMMA_SEPARATED_VALUES = true
SPLIT_BEFORE_FIRST_ARGUMENT = true
SPLIT_BEFORE_DOT = true
COALESCE_BRACKETS = true
