[pytest]

# Avoid re-printing INFO logs captured from accuracy tests
log_cli = 1
log_cli_level = WARNING
log_cli_format = %(message)s

# pytest-mock should use Pypi's mock rather than Python's built-in
mock_use_standalone_module = true

markers =
    llm: mark a test which tests brevitas_examples/llm
    onnx_export: mark a test for onnx_export in brevitas_examples/llm
    lighteval: mark a test for lighteval in brevitas_examples/llm
    lm_eval: mark a test for lm_eval in brevitas_examples/llm
    diffusion: mark a test which tests brevitas_examples/stable_diffusion
    vision: mark a test which tests brevitas_examples/imagenet_classification
