act_calibration: false
act_equalization: layerwise
act_equalization_alpha: 0.8
bias_corr: false
checkpoint_name: null
convert_layernorm_to_rmsnorm: false
dataset: wikitext2
eval: true
export_prefix: null
export_target: null
few_shot_compile: false
few_shot_eval: false
few_shot_limit: null
few_shot_tasks:
- arc_challenge
- arc_easy
- winogrande
- piqa
few_shot_zeroshot: true
fuse_sequences: false
gpfq: false
gptq: false
gpxq_act_order: false
gpxq_block_name: null
gpxq_create_weight_orig: false
gpxq_max_accumulator_bit_width: null
gpxq_max_accumulator_tile_size: null
gpxq_use_quant_activations: false
input_bit_width: 4
input_group_size: 32
input_param_method: stats
input_quant_format: int
input_quant_granularity: per_group
input_quant_type: sym
input_scale_precision: po2_scale
input_scale_type: dynamic
learned_round: null
learned_round_fast_update: false
learned_round_iters: 200
learned_round_lr: 0.005
learned_round_scale: false
learned_round_scale_lr: 0.01
learned_round_scale_momentum: 0.9
ln_affine_merge: false
load_awq: null
model: facebook/opt-125m
no_float16: true
no_quantize: false
nsamples: 128
optimize_rotations: false
quant_sdpa: false
quantize_input_zero_point: false
quantize_last_layer: false
quantize_weight_zero_point: false
replace_mha: false
replace_rmsnorm: false
rotation: null
rotation_mode: had
rotation_orphan_sink: false
scale_rounding_func_type: ceil
scaling_min_val: 0.0001
seed: 0
seqlen: 2048
weight_bit_width: 4
weight_equalization: false
weight_group_dim: null
weight_group_size: 32
weight_param_method: mse
weight_quant_format: int
weight_quant_granularity: per_group
weight_quant_type: sym
weight_scale_precision: po2_scale
