act_bit_width:
- 8
act_equalization:
- null
act_exponent_bit_width:
- 3
act_mantissa_bit_width:
- 4
act_quant_calibration_type:
- stats
act_quant_granularity:
- per_tensor
act_quant_percentile:
- 99.999
act_quant_type:
- sym
act_scale_computation_type:
- static
batch_size_calibration:
- 64
batch_size_validation:
- 256
bias_bit_width:
- 32
bias_corr:
- false
- true
calibrate_bn:
- false
calibration_dir:
- null
calibration_samples:
- 1000
channel_splitting_ratio:
- 0.0
channel_splitting_split_input:
- false
compile:
- false
dtype:
- float
export_dir:
- .
export_onnx_qcdq:
- false
export_torch_qcdq:
- false
gpfq:
- false
gpfq_p:
- 1.0
gptq:
- false
gptq_use_quant_activations:
- false
gpu:
- null
gpxq_accumulator_bit_width:
- null
gpxq_accumulator_tile_size:
- null
gpxq_act_order:
- false
gpxq_create_weight_orig:
- false
graph_eq_iterations:
- 20
graph_eq_merge_bias:
- true
layerwise_first_last_bit_width:
- 8
layerwise_first_last_exponent_bit_width:
- 3
layerwise_first_last_mantissa_bit_width:
- 4
learned_round:
- null
learned_round_batch_size:
- 1
learned_round_block_name:
- layer\d+
learned_round_iters:
- 1000
learned_round_loss:
- regularised_mse
learned_round_lr:
- 0.001
learned_round_lr_scheduler:
- null
learned_round_mode:
- layerwise
merge_bn:
- true
model_name:
- resnet18
onnx_opset_version:
- null
optimizer:
- adam
quant_format:
- int
scale_factor_type:
- float_scale
target_backend:
- fx
uint_sym_act_for_unsigned_values:
- true
validation_dir:
- null
weight_bit_width:
- 8
weight_exponent_bit_width:
- 3
weight_mantissa_bit_width:
- 4
weight_narrow_range:
- false
weight_quant_calibration_type:
- stats
weight_quant_granularity:
- per_tensor
weight_quant_type:
- sym
workers:
- 8
