dataset:
- c4
- pile
- wikitext2
dtype:
- bfloat16
eval:
- true
fuse_documents:
- true
- false
model:
- facebook/opt-125m
bos_preprocessing:
- null
- sequence
- document
add_eos_token:
- false
- true
no_quantize:
- true
nsamples:
- 2
seed:
- 0
seqlen:
- 512
