data: # root path of train/validation data (either relative/absoulte path is ok)
  train: '/datasets/LJSpeech/LJSpeech-1.1/wavs_train'
  validation: '/datasets/LJSpeech/LJSpeech-1.1/wavs_val'
  checkpoint: 'checkpoints/gener_quant_resclip_unity_02012020_c7d5cdc_0725.pt'
  name: 'gener_quant_allconst_07012020'
  result_dir: '/results/'
---
train:
  seed: 123456
  rep_discriminator: 1
  num_workers: 32
  batch_size: 16
  optimizer: 'adam'
  adam:
    lr: 0.0001
    beta1: 0.5
    beta2: 0.9
---
audio:
  n_mel_channels: 80
  segment_length: 16000
  pad_short: 2000
  filter_length: 1024
  hop_length: 256 # WARNING: this can't be changed.
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 0.0
  mel_fmax: 8000.0
---
model:
  feat_match: 10.0
---
log:
  summary_interval: 1
  validation_interval: 5
  save_interval: 25
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
firstblock_activation_configuration:
  bit_width : 8
  max_val : 1
  min_val : -1
  quant_type: 'QuantType.INT'
  scaling_impl_type : 'CONST'
  scaling_stats_op : 'MAX'
  scaling_min_val : 0.0000000002
---
firstblock_weight_configuration:
  weight_bit_width : 8
  weight_quant_type : 'QuantType.INT'
  weight_narrow_range : True
  weight_scaling_impl_type : 'PARAMETER_FROM_STATS'
  weight_scaling_stats_op : 'MAX'
  weight_scaling_min_val : 0.0000000002
  bias_bit_width : 8
  bias_quant_type : 'QuantType.FP'
  bias_narrow_range : False
  compute_output_scale : False
  compute_output_bit_width : False
---
upsamplingblock_activation_configuration:
  bit_width : 8
  max_val : 1
  min_val : -1
  quant_type: 'QuantType.INT'
  scaling_impl_type : 'CONST'
  scaling_stats_op : 'MAX'
  scaling_min_val : 0.0000000002
---
upsamplingblock_weight_configuration:
  weight_bit_width : 8
  weight_quant_type : 'QuantType.INT'
  weight_narrow_range : True
  weight_scaling_impl_type : 'PARAMETER_FROM_STATS'
  weight_scaling_stats_op : 'MAX'
  weight_scaling_min_val : 0.0000000002
  bias_bit_width : 8
  bias_quant_type : 'QuantType.FP'
  bias_narrow_range : False
  compute_output_scale : False
  compute_output_bit_width : False
---
lastblock_activation_configuration:
  bit_width: 16
  max_val: 1
  min_val: -1
  quant_type: 'QuantType.INT'
  scaling_impl_type: 'CONST'
  scaling_stats_op: 'MAX'
  scaling_min_val: 0.0000000002
---
lastblock_weight_configuration:
  weight_bit_width: 8
  weight_quant_type: 'QuantType.INT'
  weight_narrow_range: True
  weight_scaling_impl_type: 'PARAMETER_FROM_STATS'
  weight_scaling_stats_op: 'MAX'
  weight_scaling_min_val: 0.0000000002
  bias_bit_width: 8
  bias_quant_type: 'QuantType.FP'
  bias_narrow_range: False
  compute_output_scale: False
  compute_output_bit_width: False
---
residual_activation_configuration:
  bit_width : 8
  max_val : 1
  min_val : -1
  quant_type: 'QuantType.INT'
  scaling_impl_type : 'CONST'
  scaling_stats_op : 'MAX'
  scaling_min_val : 0.0000000002
---
residual_weight_configuration:
  weight_bit_width : 8
  weight_quant_type : 'QuantType.INT'
  weight_narrow_range : True
  weight_scaling_impl_type : 'PARAMETER_FROM_STATS'
  weight_scaling_stats_op : 'MAX'
  weight_scaling_min_val : 0.0000000002
  bias_bit_width : 8
  bias_quant_type : 'QuantType.FP'
  bias_narrow_range : False
  compute_output_scale : False
  compute_output_bit_width : False
---
IGNORE_MISSING_KEYS: False

