name: Test Notebook execution

on:
  push:
    branches: [ master, dev ]
  pull_request:
    types:
      - review_requested
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false


      matrix:
        python_version: ['3.7', '3.8']
        pytorch_version: ['1.5.1', '1.6.0', '1.7.1', '1.8.1', '1.9.1', '1.10.1', '1.11.0', '1.12.1', '1.13.0']
        platform: ['windows-latest', 'ubuntu-latest', 'macos-latest']


        exclude:
          - pytorch_version: '1.5.1'

          - pytorch_version: '1.6.0'

          - pytorch_version: '1.7.1'

          - platform: 'macos-latest'



    if: ${{ !github.event.pull_request.draft || contains(github.event.comment.body, '/run_tests') }}
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: ${{ matrix.python_version }}

    - name: Install Nox dependencies
      shell: bash
      run: pip install -r requirements/requirements-nox.txt

    - name: Install libsndfile and libgomp1 on Ubuntu
      shell: bash
      run: sudo apt-get install -y libsndfile-dev libgomp1
      if: startsWith(runner.os, 'Linux') == true

    - name: Install libomp on macOS
      shell: bash
      run: brew install libomp
      if: startsWith(runner.os, 'macOS') == true

    - name: Run Nox session for Notebook execution
      shell: bash
      run: nox -v -s tests_brevitas_notebook-${{ matrix.python_version }}\(\pytorch_${{ matrix.pytorch_version }}\)
