name: Test Brevitas-ORT integration

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.6', '3.7', '3.8']
        pytorch_version: ['1.1.0', '1.2.0', '1.3.1', '1.4.0', '1.5.0', '1.6.0', '1.7.1']
        platform: ['windows-latest', 'ubuntu-latest', 'macos-latest']


        exclude:
          - platform: 'macos-latest'
            pytorch_version: '1.1.0'

          - pytorch_version: '1.1.0'
            python_version: '3.8'

          - pytorch_version: '1.2.0'
            python_version: '3.8'

          - pytorch_version: '1.3.1'
            python_version: '3.8'



    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: ${{ matrix.python_version }}

    - name: Install Nox dependencies
      shell: bash
      run: pip install -r requirements/requirements-nox.txt

    - name: Install libsndfile on Ubuntu
      shell: bash
      run: sudo apt-get install -y libsndfile-dev
      if: startsWith(runner.os, 'Linux') == true

    - name: Install libomp on macOS
      shell: bash
      run: brew install libomp
      if: startsWith(runner.os, 'macOS') == true

    - name: Run Nox session for Brevitas-ORT integration
      shell: bash
      run: nox -v -s tests_brevitas_ort_integration-${{ matrix.python_version }}\(\pytorch_${{ matrix.pytorch_version }}\)


